language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: kmnoRy63Bt9kZ1jsDvDUs23C0G+yvwgEzEOb3sKuSxfptmUBgQEaCIqQQQf74K0fcKKIJQ3crOFpDBUfz7vmjvjNcTuJTq/U0FyAO0fU7TA2Ni7RKHILX97jMZ6UY1xeaou/YUIQW4ztj/zs5YDxk0X6lVuW3D+qsXSiMDxnIptZGWJ43zjkQyyrXCMUcHsXoRsHWhu08sH2ZHY/7UGEil/wVW/f4Ner28dqUs91NDSLYkl9qEI4JLI6C350FTG3nl2eJ8m82T7jOPMAmLUQ8jZ7VBGdgs1aI4IKq/Wh9H5WJZnPv9vNYRK7tksCD23DAWUVyhVAr0cDvB3I9WtuLDbJ4eEpYRbei3FNVAU2+lz5SMEw7dxL0WHWmehp7abFNmB7UdYj6EynFkY1M0zbgbEjoLQaqQuI+CLibmjF52jOVQl/2sbS6q3xZQWpBwOB/TgaDAI+QhLbak3Q7yw77h+hVSjjESOGMGsX3dKQ4IY2gTnqtobHg6qqgUeVzlhwmrnZM0D8eoFkNy24/D1um5qUUAWGtVnucwRglzqWtNCF4YixjbZKaoiP0NW07VpyKX79MoPGmjt21JL5ILHMy18RCb4DtJ0nRV2/ILEu6ep/IPorjF6IMcgb4Mk9rT+HqL41yDtoELxEofdTL8XFDh/Q/sKZA3OXCGUZ+s9p6Po=
  app: field-of-dreams
  run: rails db:migrate
