langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: AIzaSyCkfGbfjMF_fBgGBC1rupRHfY611pdShhE
  app: brownfield-of-dreams
  run: rails db:migrate
